export interface Country {
  code: string;
  name: string;
  nameEs: string;
}

export const COUNTRIES: Country[] = [
  { code: "ar", name: "Argentina", nameEs: "Argentina" },
  { code: "au", name: "Australia", nameEs: "Australia" },
  { code: "at", name: "Austria", nameEs: "Austria" },
  { code: "be", name: "Belgium", nameEs: "Bélgica" },
  { code: "br", name: "Brazil", nameEs: "Brasil" },
  { code: "ca", name: "Canada", nameEs: "Canadá" },
  { code: "cl", name: "Chile", nameEs: "Chile" },
  { code: "cn", name: "China", nameEs: "China" },
  { code: "co", name: "Colombia", nameEs: "Colombia" },
  { code: "hr", name: "Croatia", nameEs: "Croacia" },
  { code: "cz", name: "Czech Republic", nameEs: "República Checa" },
  { code: "dk", name: "Denmark", nameEs: "Dinamarca" },
  { code: "ec", name: "Ecuador", nameEs: "Ecuador" },
  { code: "eg", name: "Egypt", nameEs: "Egipto" },
  { code: "fi", name: "Finland", nameEs: "Finlandia" },
  { code: "fr", name: "France", nameEs: "Francia" },
  { code: "de", name: "Germany", nameEs: "Alemania" },
  { code: "gr", name: "Greece", nameEs: "Grecia" },
  { code: "hu", name: "Hungary", nameEs: "Hungría" },
  { code: "in", name: "India", nameEs: "India" },
  { code: "id", name: "Indonesia", nameEs: "Indonesia" },
  { code: "ie", name: "Ireland", nameEs: "Irlanda" },
  { code: "il", name: "Israel", nameEs: "Israel" },
  { code: "it", name: "Italy", nameEs: "Italia" },
  { code: "jp", name: "Japan", nameEs: "Japón" },
  { code: "mx", name: "Mexico", nameEs: "México" },
  { code: "ma", name: "Morocco", nameEs: "Marruecos" },
  { code: "nl", name: "Netherlands", nameEs: "Países Bajos" },
  { code: "nz", name: "New Zealand", nameEs: "Nueva Zelanda" },
  { code: "no", name: "Norway", nameEs: "Noruega" },
  { code: "pe", name: "Peru", nameEs: "Perú" },
  { code: "ph", name: "Philippines", nameEs: "Filipinas" },
  { code: "pl", name: "Poland", nameEs: "Polonia" },
  { code: "pt", name: "Portugal", nameEs: "Portugal" },
  { code: "ro", name: "Romania", nameEs: "Rumania" },
  { code: "ru", name: "Russia", nameEs: "Rusia" },
  { code: "sa", name: "Saudi Arabia", nameEs: "Arabia Saudita" },
  { code: "rs", name: "Serbia", nameEs: "Serbia" },
  { code: "sg", name: "Singapore", nameEs: "Singapur" },
  { code: "sk", name: "Slovakia", nameEs: "Eslovaquia" },
  { code: "za", name: "South Africa", nameEs: "Sudáfrica" },
  { code: "kr", name: "South Korea", nameEs: "Corea del Sur" },
  { code: "es", name: "Spain", nameEs: "España" },
  { code: "se", name: "Sweden", nameEs: "Suecia" },
  { code: "ch", name: "Switzerland", nameEs: "Suiza" },
  { code: "th", name: "Thailand", nameEs: "Tailandia" },
  { code: "tr", name: "Turkey", nameEs: "Turquía" },
  { code: "ae", name: "United Arab Emirates", nameEs: "Emiratos Árabes Unidos" },
  { code: "gb", name: "United Kingdom", nameEs: "Reino Unido" },
  { code: "us", name: "United States", nameEs: "Estados Unidos" },
  { code: "uy", name: "Uruguay", nameEs: "Uruguay" },
  { code: "ve", name: "Venezuela", nameEs: "Venezuela" },
];

export const F1_TEAMS = [
  "McLaren",
  "Ferrari",
  "Red Bull Racing",
  "Mercedes",
  "Aston Martin",
  "Alpine",
  "Williams",
  "Racing Bulls",
  "Haas",
  "Kick Sauber",
] as const;
